language: node_js
node_js:
  - "node"
script:
  - yarn run lint
  - yarn run test
branches:
  only:
    - master
after_success:
  - cat ./coverage/lcov.info|./node_modules/coveralls/bin/coveralls.js
  